// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function DownloadHistory() {
  return window['go']['main']['App']['DownloadHistory']();
}

export function ExtractLink(arg1) {
  return window['go']['main']['App']['ExtractLink'](arg1);
}

export function GetDownloadSettings() {
  return window['go']['main']['App']['GetDownloadSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveDownloadSettings(arg1) {
  return window['go']['main']['App']['SaveDownloadSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function Transform(arg1) {
  return window['go']['main']['App']['Transform'](arg1);
}
