// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tools} from '../models';
import {configs} from '../models';
import {main} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function Download(arg1:tools.ExtractLinkData):Promise<void>;

export function DownloadHistory():Promise<void>;

export function ExtractLink(arg1:string):Promise<Array<tools.ExtractLinkData>>;

export function GetDownloadSettings():Promise<configs.DownloadConfig>;

export function Greet(arg1:string):Promise<string>;

export function SaveDownloadSettings(arg1:configs.DownloadConfig):Promise<void>;

export function SelectDirectory():Promise<Array<main.NcmFile>>;

export function Transform(arg1:Array<main.NcmFile>):Promise<void>;
